# Generated by Django 5.0.1 on 2024-04-23 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_nsb_certificaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='empTipoContrato',
            field=models.CharField(db_comment='Tipo de contrato del empleado', default='Término Fijo', max_length=100),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='empCedula',
            field=models.CharField(db_comment='Numero de cedula del empleado', max_length=20),
        ),
    ]
