# Generated by Django 5.0.1 on 2024-01-24 18:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_nsb_certificaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empNombre', models.CharField(db_comment='Nombre del empleado', max_length=100)),
                ('empCedula', models.CharField(db_comment='Numero de cedula del empleado', max_length=20)),
                ('empCargo', models.CharField(choices=[('Madre comunitaria', 'Madre comunitaria'), ('Docente', 'Docente'), ('Padre comunitario', 'Padre comunitario'), ('Auxiliar administrativo', 'Auxiliar administrativo')], db_comment='Cargo del empleado', max_length=100)),
                ('empFechaHoraCreacion', models.DateTimeField(auto_now_add=True, db_comment='Fecha y hora del registro')),
                ('empFechaHoraActualizacion', models.DateTimeField(auto_now=True, db_comment='Fecha y hora última actualización')),
            ],
        ),
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cerNombre', models.CharField(db_comment='Nombre del certificado', max_length=100)),
                ('cerFechaHoraCreacion', models.DateTimeField(auto_now_add=True, db_comment='Fecha y hora del registro')),
                ('cerFechaHoraActualizacion', models.DateTimeField(auto_now=True, db_comment='Fecha y hora última actualización')),
                ('cerUser', models.ForeignKey(db_comment='Usuario que crea el certificado', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('cerEmpleado', models.ForeignKey(db_comment='Empleado al que pertenece el certificado', on_delete=django.db.models.deletion.CASCADE, to='app_nsb_certificaciones.empleado')),
            ],
        ),
    ]
